import datetime
from typing import List, Dict, Any, Optional
from ..models.evidence import EvidenceItem, CausalLink
from ..models.contradiction import ContradictionItem

class ReportGenerator:
    def generate_report(
        self,
        investigation_id: str,
        question: str,
        answer: str,
        root_cause: Optional[str],
        confidence: float,
        confidence_level: str,
        evidence: List[EvidenceItem],
        causal_chain: List[CausalLink],
        contradictions: List[ContradictionItem],
        unresolved_questions: List[str]
    ) -> str:
        date_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        
        lines = [
            f"# NEXUS INVESTIGATION REPORT: {investigation_id}",
            f"**Autonomous Enterprise Investigation System**",
            f"*Generated: {date_str}* | *Mode: Local Evidence Mode* | *Evidence Confidence: {int(confidence*100)}% ({confidence_level})*",
            "",
            "---",
            "",
            "## 1. Investigation Question",
            f"> {question}",
            "",
            "## 2. Executive Summary",
            answer,
            "",
            "## 3. Key Findings",
        ]
        
        for ev in evidence[:4]:
            lines.append(f"- **[{ev.document_id}] {ev.title}** ({ev.department}, {ev.date}): {ev.summary} *(Strength: {int(ev.strength*100)}%)*")
            
        lines.extend([
            "",
            "## 4. Investigation Path",
            f"Autonomous recursive search spanned {len({e.department for e in evidence})} departmental silos and retrieved {len(evidence)} verified enterprise records.",
            f"Investigation depth reached Level {min(5, max(1, len(causal_chain)))} with active contradiction reconciliation.",
            "",
            "## 5. Evidence Chain",
        ])
        
        for i, ev in enumerate(evidence):
            lines.append(f"{i+1}. **{ev.document_id}** — *{ev.title}* | {ev.evidence_type} (Relevance: {ev.relevance}, Source: {ev.source})")
            lines.append(f"   > \"{ev.excerpt}\"")
            
        lines.extend([
            "",
            "## 6. Causal Chain",
        ])
        
        if causal_chain:
            for link in causal_chain:
                citations = f" [{', '.join(link.supporting_doc_ids)}]" if link.supporting_doc_ids else ""
                lines.append(f"- **Step {link.step_order}**: {link.cause} ➔ {link.effect}{citations}")
        else:
            lines.append("*Causal chain could not be constructed due to insufficient evidence.*")

        lines.extend([
            "",
            "## 7. Root Cause",
            f"**{root_cause or 'INSUFFICIENT EVIDENCE DETECTED'}**",
            "",
            "## 8. Supporting Evidence",
            "The findings are backed by cross-functional evidence linking operational data, telemetry, and administrative directives.",
            "",
            "## 9. Contradictions Detected",
        ])
        
        if contradictions:
            for c in contradictions:
                lines.append(f"### Conflict: {c.source_a_id} vs {c.source_b_id}")
                lines.append(f"- **Claim A ({c.source_a_id}, v{c.source_a_version}, {c.source_a_status})**: {c.claim_a}")
                lines.append(f"- **Claim B ({c.source_b_id}, v{c.source_b_version}, {c.source_b_status})**: {c.claim_b}")
                lines.append(f"- **Resolution Basis**: {c.resolution_basis}")
        else:
            lines.append("No active contradictory claims were observed in the retrieved evidence set.")

        lines.extend([
            "",
            "## 10. Resolution",
            "Conflicting records were evaluated against versioning, effective dates, and authority tiers. Verified final reports supersede preliminary projections.",
            "",
            "## 11. Unresolved Questions",
        ])
        
        for uq in unresolved_questions:
            lines.append(f"- ❓ {uq}")
            
        lines.extend([
            "",
            "## 12. Sources",
        ])
        
        seen_src = set()
        for ev in evidence:
            if ev.source not in seen_src:
                lines.append(f"- **{ev.source}** ({ev.department}) — Reliability Score: {ev.source_reliability}")
                seen_src.add(ev.source)

        lines.extend([
            "",
            "## 13. Confidence Assessment",
            f"**Overall Evidence Confidence: {int(confidence*100)}% ({confidence_level})**",
            f"- Independent Cross-Department Silos: {len({e.department for e in evidence})}",
            f"- Total Primary Documents: {len(evidence)}",
            f"- Conflicting Records Reconciled: {len(contradictions)}",
            "",
            "---",
            "*Report generated by NEXUS Autonomous Investigation Engine. All citations refer to verified records in the enterprise knowledge base.*"
        ])

        return "\n".join(lines)

report_generator = ReportGenerator()
