import React, { useEffect, useState } from 'react';
import { getInvestigations, getGraph, getDocument } from '../services/api';
import EvidenceGraph from '../components/EvidenceGraph';
import EvidencePanel from '../components/EvidencePanel';
import { Network, Layers } from 'lucide-react';

export default function KnowledgeGraph() {
  const [investigations, setInvestigations] = useState([]);
  const [selectedInvId, setSelectedInvId] = useState('');
  const [currentGraph, setCurrentGraph] = useState(null);
  const [inspectedDoc, setInspectedDoc] = useState(null);

  useEffect(() => {
    async function load() {
      try {
        const invs = await getInvestigations();
        setInvestigations(invs);

        if (invs.length > 0) {
          const firstInvId = invs[0].investigation_id;
          setSelectedInvId(firstInvId);

          // Fetch full graph for the selected investigation using central API service
          const graph = await getGraph(firstInvId);
          setCurrentGraph(graph);
        }
      } catch (err) {
        console.error('Failed to load knowledge graph:', err);
      }
    }

    load();
  }, []);

  const handleSelectInv = async (invId) => {
    setSelectedInvId(invId);

    try {
      const graph = await getGraph(invId);
      setCurrentGraph(graph);
      setInspectedDoc(null);
    } catch (err) {
      console.error('Failed to load investigation graph:', err);
      setCurrentGraph(null);
    }
  };

  const handleSelectNode = (data) => {
    if (!data?.document_id) return;

    getDocument(data.document_id)
      .then((doc) => setInspectedDoc(doc))
      .catch((err) => console.error('Failed to load document:', err));
  };

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-[var(--text-strong)]">
            Dynamic Knowledge Graph Explorer
          </h1>

          <p className="text-xs text-[var(--text-muted)] mt-1">
            Explore causal nodes, document linkages, and entity dependencies
            generated by autonomous investigations.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-[var(--text-muted)]">
            Select Case:
          </span>

          <select
            value={selectedInvId}
            onChange={(e) => handleSelectInv(e.target.value)}
            className="bg-[var(--surface)] border border-[var(--border)] text-xs text-[var(--text)] rounded-md px-3 py-1.5 font-mono focus:outline-none focus:border-violet-500"
          >
            {investigations.map((inv) => (
              <option
                key={inv.investigation_id}
                value={inv.investigation_id}
              >
                {inv.investigation_id}: {inv.question.substring(0, 40)}...
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="h-[640px] bg-[var(--bg)] rounded-lg border border-[var(--border)] overflow-hidden">
        <EvidenceGraph
          graph={currentGraph}
          onSelectNode={handleSelectNode}
        />
      </div>

      {inspectedDoc && (
        <EvidencePanel
          document={inspectedDoc}
          onClose={() => setInspectedDoc(null)}
        />
      )}
    </div>
  );
}
